server:
  port: 8080

spring:
  profiles:
    active: "default"
  application:
    name: "user-microservice"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    username: "root"
    password: "password"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/aline_financial"
    initialization-mode: always

management.endpoints.web.exposure.include: '*'


app:
  admin-portal: "${PORTAL_ADMIN}"
  member-dashboard: "${PORTAL_DASHBOARD}"
  landing-portal: "${PORTAL_LANDING}"
  sms:
    enable: true
  email:
    from: "no-reply@alinefinancial.com"
    enable: true
  security:
    secret-key: "xBnkRrjIeZvtl3864JbRjg5rpLhZPneH"
    jwt:
      secret-key: "7y5Phi01FZzd60UJMkGinerMiBgNy4DP"
  aws:
    email:
      template-bucket-name: "aline-email-templates"
    credentials:
      access-key-id: "${APP_USER_ACCESS_KEY}"
      secret-access-key: "${APP_USER_SECRET_KEY}"

